version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: job-queue-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: queue
      POSTGRES_PASSWORD: queue
      POSTGRES_DB: queue
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
